// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpuYOuO6QDizPd1lvsUbjP3luGPMEH_LE',
    appId: '1:31612468599:web:5acad8dae2d5c4dc7fb572',
    messagingSenderId: '31612468599',
    projectId: 'flutter-chat-app-4a67e',
    authDomain: 'flutter-chat-app-4a67e.firebaseapp.com',
    storageBucket: 'flutter-chat-app-4a67e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlY4P5J22c0OvWMWeYXjicndJSZp0CLac',
    appId: '1:31612468599:android:fd0b88f05f611ea57fb572',
    messagingSenderId: '31612468599',
    projectId: 'flutter-chat-app-4a67e',
    storageBucket: 'flutter-chat-app-4a67e.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpuYOuO6QDizPd1lvsUbjP3luGPMEH_LE',
    appId: '1:31612468599:web:94dac4f4f1fc38227fb572',
    messagingSenderId: '31612468599',
    projectId: 'flutter-chat-app-4a67e',
    authDomain: 'flutter-chat-app-4a67e.firebaseapp.com',
    storageBucket: 'flutter-chat-app-4a67e.appspot.com',
  );

}